let newsData = [
    {
        id: 1,
        title: "Первый соревновательный день по компетенции «Преподавание в младших классах» (юниоры)",
        description: "... час (участник использует материалы, указанные в инфраструктурном листе) Лимит времени на представление задания: 15 мин Контингент: волонтеры (6 человек) Задание: Подготовка к демонстрации фрагмента ...",
        date: "20 марта 2024",
        image: "/assets/images/news/news1.webp",
        href: "news/1",
        information: news1,
        photos: [
            { img: "/assets/images/news/news1-1.webp", id: 1 },
            { img: "/assets/images/news/news1-2.webp", id: 2 },
            { img: "/assets/images/news/news1-3.webp", id: 3 },
            { img: "/assets/images/news/news1-4.webp", id: 4 },
        ],
    },
    {
        id: 2,
        title: "Мастер-класс «Педагогические условия организация общения в ДОО»",
        description: "... Ответственный Кедяркина Н.В., Шевчук П.Н.- 4 курс, волонтеры 344б гр. Цель — формирование общих и профессиональных компетенцией по созданию и организации условий для общения и взаимодействия детей в ...",
        date: "15 февраля 2024",
        image: "/assets/images/news/news2.webp",
        href: "news/2",
        information: news2,
        photos: [
            { img: "/assets/images/news/news2-1.webp", id: 1 },
            { img: "/assets/images/news/news2-2.webp", id: 2 },
            { img: "/assets/images/news/news2-3.webp", id: 3 },
            { img: "/assets/images/news/news2-4.webp", id: 4 },
            { img: "/assets/images/news/news2-5.webp", id: 5 },
        ],
    },
    {
        id: 3,
        title: "Второй соревновательный день на площадках чемпионата профессионального мастерства «Профессионалы»",
        description: "... 15 минут – представление) Контингент: волонтеры - 6 человек Задания: Подготовка к проведению обучающего интерактива по заданной теме. Определить цель и задачи интерактивного взаимодействия. Осуществить ...",
        date: "07 апреля 2023",
        image: "/assets/images/news/news3.webp",
        href: "news/3",
        information: news3,
        photos: [
            { img: "/assets/images/news/news3-1.webp", id: 1 },
            { img: "/assets/images/news/news3-2.webp", id: 2 },
            { img: "/assets/images/news/news3-3.webp", id: 3 },
            { img: "/assets/images/news/news3-4.webp", id: 4 },
            { img: "/assets/images/news/news3-5.webp", id: 5 },
        ],
    },
    {
        id: 4,
        title: "Заседание дискуссионного клуба «Коллоквиум»",
        description: "... и администрации. На мероприятии присутствовали волонтеры, которые представили свою деятельность, члены студенческого актива. Все участники  клуба считают необходимым проводить общение в таком формате, ...",
        date: "25 февраля 2020",
        image: "/assets/images/news/news4.webp",
        href: "news/4",
        information: news4,
        photos: [
            { img: "/assets/images/news/news4-1.webp", id: 1 },
            { img: "/assets/images/news/news4-2.webp", id: 2 },
            { img: "/assets/images/news/news4-3.webp", id: 3 },
        ],
    },
    {
        id: 5,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/5",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
    {
        id: 6,
        title: "Волонтеры центра Абилимпикс, в библиотеке имени Мельникова - Печерского",
        description: "Сегодня члены волонтерского центра Абилимпикс Нижегородской области и \"Поколение NEXT\" на базе ГБПОУ Нижегородского Губернского колледжа, делились своим опытом с активом учащихся старших классов школы ...",
        date: "09 декабря 2019",
        image: "/assets/images/news/news6.webp",
        href: "news/6",
        information: news6,
        photos: [
            { img: "/assets/images/news/news6-1.webp", id: 1 },
            { img: "/assets/images/news/news6-2.webp", id: 2 },
            { img: "/assets/images/news/news6-3.webp", id: 3 },
            { img: "/assets/images/news/news6-4.webp", id: 4 },
        ],
    },
    {
        id: 7,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/7",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 8,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/8",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 9,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/9",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 10,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/10",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 11,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/11",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 12,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/12",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
        {
        id: 13,
        title: "Клуб болельщиков",
        description: "Клуб болельщиков сегодня активно поддерживал конкурсантов. Волонтеры выполняли задания, участвовали в демонстрации урока в роли учеников и переживали вместе с участниками отборочных соревнований.",
        date: "05 августа 2020",
        image: "/assets/images/news/news5.webp",
        href: "news/13",
        information: news5,
        photos: [
            { img: "/assets/images/news/news5-1.webp", id: 1 },
            { img: "/assets/images/news/news5-2.webp", id: 2 },
        ],
    },
];